# Generated by Django 3.2.8 on 2021-11-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_item_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(db_column='ID_user', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('age', models.IntegerField(db_column='Age')),
                ('weight', models.DecimalField(db_column='Weight', decimal_places=2, max_digits=3)),
                ('sex', models.TextField(db_column='Sex')),
                ('height', models.DecimalField(db_column='Height', decimal_places=1, max_digits=3)),
                ('goal', models.DecimalField(blank=True, db_column='Goal', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='to_do_list',
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id_meal', models.OneToOneField(db_column='ID_meal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.user')),
                ('date', models.DateTimeField(db_column='Date')),
                ('amount', models.IntegerField(db_column='Amount')),
            ],
            options={
                'db_table': 'Meal',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id_food', models.OneToOneField(db_column='ID_food', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.meal')),
                ('kcal', models.SmallIntegerField(db_column='Kcal')),
                ('weight', models.DecimalField(db_column='Weight', decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(blank=True, db_column='Carbohydrates', decimal_places=2, max_digits=6, null=True)),
                ('fats', models.DecimalField(blank=True, db_column='Fats', decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'Food',
                'managed': False,
            },
        ),
    ]
