# Generated by Django 3.2.8 on 2021-11-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211121_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProperties'
        ),


    ]
