# Generated by Django 3.2.8 on 2021-11-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20211122_0233'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userproperties',
            table='UserProperties',
        ),

    ]
