# Generated by Django 3.2.8 on 2021-12-09 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_alter_userproperties_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_properties',
            fields=[
                ('id_user', models.AutoField(db_column='ID_user', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('age', models.IntegerField(db_column='Age')),
                ('weight', models.DecimalField(db_column='Weight', decimal_places=2, max_digits=3)),
                ('sex', models.BooleanField(db_column='Sex')),
                ('height', models.DecimalField(db_column='Height', decimal_places=1, max_digits=3)),
                ('goal', models.DecimalField(blank=True, db_column='Goal', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'user_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProperties',
        ),
        migrations.AddField(
            model_name='item',
            name='to_do_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.todolist'),
        ),
    ]
